.ALIASES
V_Vdd           Vdd(+=VDD -=0 ) CN @MRL_NOVEL.SCHEMATIC1(sch_1):INS98@SOURCE.VDC.Normal(chips)
V_Vin1          Vin1(+=VIN1 -=0 ) CN @MRL_NOVEL.SCHEMATIC1(sch_1):INS260@SOURCE.VPWL_FILE.Normal(chips)
M_T4            T4(d=N01597 g=VIN1 s=VDD s=VDD ) CN @MRL_NOVEL.SCHEMATIC1(sch_1):INS1287@BREAKOUT.MbreakP3.Normal(chips)
M_M3            M3(d=N01597 g=VIN1 s=VIN1 b=0 ) CN @MRL_NOVEL.SCHEMATIC1(sch_1):INS2830@BREAKOUT.MbreakN.Normal(chips)
_    _(Vdd=VDD)
_    _(Vin1=VIN1)
.ENDALIASES
